---
# handlers file for omero-prometheus-exporter

- name: Restart prometheus-omero-exporter
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: prometheus-omero-exporter
    state: restarted
