---
# handlers file for omero-prometheus-exporter

- name: restart prometheus-omero-exporter
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: prometheus-omero-exporter
    state: restarted
